### PR TITLE
Fix file generation

### LINKED ISSUE #22: PHP Fatal error:  Uncaught Error: Call to a member function compile() on null
I try to use this package with fresh installation of **laminas-mvc-skeleton** everything works perfect except this error @weierophinney  or @rieschl  Do you have any ides why **$listener** is not getting this **compile** method

image

I tried to debug more on this and found that, While **entries by tag** is compiled at that time **$listener** become null.

image

### PR DESCRIPTION
**Pull request by rieschl**
* attach the listeners before compiling
* set some more services in ViewFactory

fixes #22

### CODE REVIEW

**Comment by vrkansagara** [comment]
LGTM :+1:  @weierophinney  and @rieschl

**Comment by weierophinney** [comment]
I've actually found a simpler way to do the view factory that ensures everything is setup correctly. The one issue I'm still running into, however, is that the layout is not being used in the generated files. Is that part working for you?

**Comment by rieschl** [comment]
> I've actually found a simpler way to do the view factory that ensures everything is setup correctly. The one issue I'm still running into, however, is that the layout is not being used in the generated files. Is that part working for you?

I haven't checked that, yet. But @vrkansagara said that he got that managed by attaching a new response strategy:

```
ohk , I got fix by adding this code.
 $layout = new ViewModel();
 $layout->setTemplate('layout');
 $view->addResponseStrategy(function ($e) use ($layout, $renderer) {
     $result = $e->getResult();
     $layout->setVariable('content', $result);
     $page = $renderer->render($layout);
     $e->setResult($page);
 
 }, 100);
```

**Comment by weierophinney** [comment]
@vrkansagara reached out to me as well with that response strategy solution. That leads to another issue for me: helpers are stateful, and the compiler runs in a single process... which means that it aggregates things like the title, meta tags, script tags, etc. Each request either prepends or appends the exact same values... which means that by the end, on my testbed of ~300 posts, I get quite the redundancy! As such, I need to find a solution for making the view stateless between renders as well.

**Comment by weierophinney** [comment]
Closing in favor of #26 - I identified how to fix the state issues. :smile:

**Pull request closed without merging**
